name: MiracleSheepEssentials
version: 1.0
author: MiracleSheep
main: com.MiracleSheep.MiracleSheepEssentials.MiracleSheepEssentials
api-version: 1.14
depend:
commands:
  rules:
    description: Lists the rules of the server
    usage: /<command>
    aliases: [law]
  boom:
    description:  Summons a boomrod
    usage: /<command>
    aliases: [boomrod]
  invsave:
    description: Saves your inventory
    usage: /<command>
  invload:
    description: Loads an inventory
    usage: /<command>
  invsavei:
    description: Saves your inventory by someone else
    usage: /<command>
  invloadi:
    description: Loads an inventory by someone else
    usage: /<command>

